site_name: JED-FFM Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tooltips
extra_css:
  - assets/custom.css
extra:
  state:
    - video
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/engr-iliyas/JED-FFM
      name: GitHub Repository
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/engrmn
      name: LinkedIn Profile
  generator: false # Hides "Made with MkDocs"
  footer: |
    2024 JED Plc - Field Force Management (FFM)  
    Version: 1.0.0 | Last Updated: March 2025  
    📧 Support: <a href="mailto:support@jedplc.com">support@jedplc.com</a>  
    🔗 <a href="/privacy-policy/">Privacy Policy</a> | <a href="/terms/">Terms of Use</a>  
    🚀 Developed by JED Plc IT Team
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Overview: index.md
  - Getting Started:
      - Overview: getting_started.md
      - Login Page: login_page.md
      - Home Page: home_page.md
      - Extension:
          - Show in Map: extension_map.md
          - Open in Excel: extension_excel.md
          - Open in Google Earth: extension_google_earth.md
          - Contact: extension_contact.md
  - Quick Actions:
      - Bill Delivery: bill_delivery.md
      # - Posting Payment: posting_payment.md
      # - Scheduling Disconnection: scheduling_disconnection.md
      # - Validating a Customer: validating_customer.md
  - Quick Trackers:
      - Activities Today: activities_today.md
  - Quick Pages:
      - Activities Today: activities_today.md
  - Staff: staff.md
